In [42]:
import vtk
import numpy as np

In [43]:
x_vals = np.load('x_vals.npy')
y_vals = np.load('y_vals.npy')
z_vals = np.load('z_vals.npy')
var_vals = np.load('var_vals.npy')

In [44]:
print(np.shape(x_vals),np.shape(y_vals),np.shape(z_vals))

(5740,) (5740,) (5740,)


In [45]:
np.shape(var_vals)

(5740,)

In [46]:
x_vals

array([0.89031339, 3.56125356, 8.01282051, ..., 6.92775107, 6.95557336,
       6.98339566])

In [47]:
y_vals


array([ 5.78703704,  2.22578348, 10.68376068, ...,  5.48099181,
        5.67574786,  5.39752493])

In [48]:
z_vals[:1000]

array([ 0.        ,  0.4451567 ,  0.4451567 ,  0.4451567 ,  1.33547009,
        3.11609687,  3.11609687,  3.56125356,  3.56125356,  3.56125356,
        4.00641026,  4.00641026,  4.00641026,  4.00641026,  4.45156695,
        4.45156695,  4.45156695,  4.45156695,  4.89672365,  5.34188034,
        5.34188034,  5.34188034,  5.34188034,  5.78703704,  5.78703704,
        5.78703704,  6.23219373,  6.23219373,  6.67735043,  7.12250712,
        7.56766382,  8.01282051,  8.45797721,  9.3482906 ,  9.79344729,
        9.79344729, 10.23860399, 10.68376068, 12.01923077, 12.46438746,
        0.89031339,  1.78062678,  1.78062678,  3.56125356,  5.34188034,
        5.34188034,  6.23219373,  6.23219373,  7.12250712,  8.45797721,
        9.3482906 ,  9.79344729, 10.23860399, 10.68376068, 11.12891738,
       11.12891738,  0.89031339,  0.89031339,  1.33547009,  2.22578348,
        2.22578348,  3.11609687,  3.11609687,  3.56125356,  4.45156695,
        4.89672365,  5.34188034,  5.78703704,  6.23219373,  6.67

In [49]:
x_vals = np.load('x_vals.npy')
y_vals = np.load('y_vals.npy')
z_vals = np.load('z_vals.npy')
var_vals = np.load('var_vals.npy')
name = 'density'
filename = 'test.vtp'
Points = vtk.vtkPoints()
val_arr = vtk.vtkFloatArray()
val_arr.SetNumberOfComponents(1)
val_arr.SetName(name)

tot_pts = np.size(var_vals)
for i in range(tot_pts):
#     print(i)
    Points.InsertNextPoint(x_vals[i],y_vals[i],z_vals[i])
    val_arr.InsertNextValue(var_vals[i])

polydata = vtk.vtkPolyData()
polydata.SetPoints(Points)

polydata.GetPointData().AddArray(val_arr)

polydata.Modified()

writer = vtk.vtkXMLPolyDataWriter()
print("writing file:",filename)
writer.SetFileName(filename)
if vtk.VTK_MAJOR_VERSION <= 5:
    writer.SetInput(polydata)
else:
    writer.SetInputData(polydata)
writer.Write()

writing file: test.vtp


1